[package]
name = "moore-vhdl"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../common" }
moore-vhdl-syntax = { path = "syntax" }
# moore-vhdl-hir = { path = "hir" }
bincode = "0.6"
lazy_static = "0.2"
llhd = { git = "https://github.com/fabianschuiki/llhd", rev = "b88f18f" }
num = "0.1"
rustc-serialize = "0.3"
slog = "2.0.12"
typed-arena = "1.3.0"
# futures = "0.1"
