[package]
name = "moore-vhdl"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]
edition = "2018"

description = "The VHDL implementation of the moore compiler framework."
license = "Apache-2.0 OR MIT"

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../common", version = "0.1" }
moore-vhdl-syntax = { path = "syntax", version = "0.1" }
bincode = "0.6"
lazy_static = "0.2"
llhd = "0.1"
num = "0.1"
rustc-serialize = "0.3"
slog = "2.0.12"
typed-arena = "1.3.0"
# futures = "0.1"
