max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
wrap_comments = false
normalize_comments = false
merge_derives = true
force_explicit_abi = true
unstable_features = false
format_strings = true
