[package]
name = "moore"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

description = "A compiler for hardware description languages."
documentation = "https://fabianschuiki.github.io/moore"
repository = "https://github.com/fabianschuiki/moore"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "fabianschuiki/moore", branch = "master" }

[workspace]

[dependencies]
moore-common = { path = "src/common", version = "0.1" }
moore-svlog = { path = "src/svlog", version = "0.1" }
moore-vhdl = { path = "src/vhdl", version = "0.1" }
bincode = "0.6.1"
clap = "2"
llhd = "0.1"
num = "0.1"
rustc-serialize = "0.3.22"
serde = "1"
sha1 = "0.2.0"
slog = "2.0.12"
typed-arena = "1.3.0"

[features]
unstable = []

[[bin]]
doc = false
name = "moore"
path = "src/bin/moore.rs"
