[package]
name = "moore"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[workspace]

[dependencies]
moore-common = { path = "src/common" }
moore-svlog = { path = "src/svlog" }
moore-vhdl = { path = "src/vhdl" }
bincode = "0.6.1"
clap = "2"
llhd = { git = "https://github.com/fabianschuiki/llhd", rev = "b88f18f" }
num = "0.1"
rustc-serialize = "0.3.22"
serde = "1"
sha1 = "0.2.0"
slog = "2.0.12"
typed-arena = "1.3.0"

[features]
unstable = []

[[bin]]
doc = false
name = "moore"
path = "src/bin/moore.rs"
