[package]
name = "moore"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@student.ethz.ch>"]
build = "pre/build.rs"

[dependencies]
memmap = "0.5.0"
owning_ref = "0.2.2"
clap = "2"
sha1 = "0.2.0"
bincode = "0.6.1"
rustc-serialize = "0.3.22"
