[package]
name = "moore-svlog"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]
edition = "2018"

description = "The SystemVerilog implementation of the moore compiler framework."
license = "Apache-2.0 OR MIT"

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../common", version = "0.1" }
moore-svlog-syntax = { path = "syntax", version = "0.1" }
llhd = "0.1"
log = "0.4"
salsa = { git = "https://github.com/fabianschuiki/salsa", branch = "database-lifetimes" }

[dev-dependencies]
simple_logger = "1"
