[package]
name = "moore-svlog"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../common" }
moore-svlog-syntax = { path = "syntax" }
moore-svlog-hir = { path = "hir" }
bincode = "0.6"
rustc-serialize = "0.3"
