[package]
name = "moore-svlog-syntax"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

description = "The SystemVerilog parser implementation of the moore compiler framework."
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../../common", version = "0.1" }
rustc-serialize = "0.3.22"
bincode = "0.6.1"
slog = "2.0.12"
