[package]
name = "moore-common"
version = "0.5.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]
edition = "2018"

description = "The common core of the moore compiler framework."
repository = "https://github.com/fabianschuiki/moore"
license = "Apache-2.0 OR MIT"

[lib]
path = "lib.rs"

[dependencies]
memmap = "0.5.0"
rustc-serialize = "0.3.22"
serde = "1"
slog = "2.0.12"
bitflags = "1.0"
typed-arena = "1.3.0"
