on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "source checkout"
      - uses: actions-rs/toolchain@v1
        name: "toolchain installation"
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: "cargo check"
        with:
          command: check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "source checkout"
      - uses: actions-rs/toolchain@v1
        name: "toolchain installation"
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: "cargo fmt"
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: "cargo clippy"
        continue-on-error: true  # TODO: Remove once we have fixed the mall
        with:
          command: clippy

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "source checkout"
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        name: "toolchain installation"
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: "cargo test"
        with:
          command: test
          args: --all
      - run: python3 scripts/test.py --debug --verbose
        name: "regression tests"
